### ISSUE TITLE
How to run a task which may need more time than the SSH time out?

### ISSUE THREAD

**Issue by don2ccc** [seantis/suitable#32]
Hello Sir @href 

Like say, I have below task defined, you can see there has "async" added.
this is because the ".run.sh" will takes very long time, usually about 3 minutes, it is for start our app server.  after added async option, it works good from cli.  

How can I do the same with Suitable API? could you advise me?

```yaml
- name: APP START
      shell: ./run.sh
      async: 1000
      poll: 0
      register: start_process
      args:
        chdir: /path/to/some/where/
      notify:
      - check_status
```

Thanks a lot!
