### ISSUE TITLE
how to use with_items ,when and tags in suitable

### ISSUE THREAD

**Issue by x2y2** [seantis/suitable#33]
suitable is very good, but i don't know how to use it with when , with_items , and tags。

**Comment by href** [comment]
Suitable doesn't support these directives, since they basically exist to add logic to Ansible playbooks (as I understand it). However, with Suitable you have Python at your disposal, so these
constructs don't make much sense I think.

For example, from the [docs](https://docs.ansible.com/ansible/latest/user_guide/playbooks_conditionals.html#the-when-statement), this statement:
```yaml
 - name: "shut down Debian flavored systems"
    command: /sbin/shutdown -t now
    when: ansible_facts['os_family'] == "Debian"
```

Would be written as follows with ansible:
```python
from suitable import Api
HOST = 'example.org'
api = Api(HOST)

# retrieve the facts
facts = api.setup().ansible_facts(HOST)

# conditional shutdown
if facts['ansible_os_family'] == 'Debian':
    api.command('/sbin/shutdown -t now')
```
